language: node_js

node_js:
  - "node"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libcairo2-dev
      - libjpeg8-dev
      - libpango1.0-dev
      - libgif-dev
      - g++-4.8
env:
  - CXX=g++-4.8

before_install:
  - npm explore npm -g -- npm install node-gyp@latest

install:
  - npm install

script:
  - npm test

notifications:
  email: false
